### ISSUE TITLE
Auto Transition is not imported due to capitalization

### ISSUE THREAD

**Issue by RaynorD** [bryce-seifert/ATEM-Macro-Snippets#1]
Hey thanks for the great snippets!

I've confirmed that macros containing the auto transition are not importing for me, and that capitalizing the T fixes the issue. 

Not working:
`<Op id="Autotransition" mixEffectBlockIndex="0"/>`

Working:
`<Op id="AutoTransition" mixEffectBlockIndex="0"/>`

For reference I'm on MacOS 10.15.7 running ATEM software control 8.5.3.

Thanks!

**Comment by bryce-seifert** [comment]
Interesting, I wonder what's causing it to not be capitalized. In the sniper code, it has the working capitalization:

```
"prefix": "AUTO Transition",
		"body": [
			"<Op id=\"AutoTransition\" mixEffectBlockIndex=\"${1|0,1,2,3|}\"/>"
		],
```

Is it appearing automatically uncapitalized?

**Comment by RaynorD** [comment]
Very strange, yes my non-working code was copy/pasted directly from the generated snippet, and I just tried it again with the same result. VS Code isn't my primary editor so I'm not super familiar, is there some way I can inspect the extension locally?

If it helps this is what I'm seeing:
<img width="447" alt="Screen Shot 2021-01-07 at 8 44 19 PM" src="https://user-images.githubusercontent.com/6573754/103968274-2323f480-5129-11eb-83aa-2588d5bdc12a.png">

**Comment by bryce-seifert** [comment]
Ah. I figured it out. This isn't my snippet. My snippet uses the prefix AUTO Transition. Looks like you've downloaded [this snippet.](https://github.com/imorrish/atem-macro-snippet).

You're welcome to submit an issue there, or download my snippet with the correct code [here](https://marketplace.visualstudio.com/items?itemName=bryceseifert.atem-macro-snippets) ;)

**Comment by RaynorD** [comment]
Gah, don't know how that happened. So sorry!
